//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantic.Controls {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantic.Controls.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_Average {
            get {
                return ResourceManager.GetString("AggregationFunction_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数(非空) 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_Count {
            get {
                return ResourceManager.GetString("AggregationFunction_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数 - 非空 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_CountParenthesized {
            get {
                return ResourceManager.GetString("AggregationFunction_CountParenthesized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数(不重复) 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_DistinctCount {
            get {
                return ResourceManager.GetString("AggregationFunction_DistinctCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数 - 不重复 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_DistinctCountParenthesized {
            get {
                return ResourceManager.GetString("AggregationFunction_DistinctCountParenthesized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_Max {
            get {
                return ResourceManager.GetString("AggregationFunction_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_Min {
            get {
                return ResourceManager.GetString("AggregationFunction_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无聚合 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_None {
            get {
                return ResourceManager.GetString("AggregationFunction_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求和 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_Sum {
            get {
                return ResourceManager.GetString("AggregationFunction_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户定义 的本地化字符串。
        /// </summary>
        public static string AggregationFunction_UserDefined {
            get {
                return ResourceManager.GetString("AggregationFunction_UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdTree分类法 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_AdTree {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_AdTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神经网络 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_ANN {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_ANN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贝叶斯 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_Bayers {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_Bayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集成法1 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_JC1 {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_JC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集成法2 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_JC2 {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_JC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 K最邻近结点 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_KNN {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_KNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SVM分类法 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_SVM {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_SVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策树分类法 的本地化字符串。
        /// </summary>
        public static string ClassificationAlgorithm_Tree {
            get {
                return ResourceManager.GetString("ClassificationAlgorithm_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑色 的本地化字符串。
        /// </summary>
        public static string Color_Black {
            get {
                return ResourceManager.GetString("Color_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝色 的本地化字符串。
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，较深 {1}% 的本地化字符串。
        /// </summary>
        public static string Color_DarkerFormat {
            get {
                return ResourceManager.GetString("Color_DarkerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深红 的本地化字符串。
        /// </summary>
        public static string Color_DarkRed {
            get {
                return ResourceManager.GetString("Color_DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深红色 的本地化字符串。
        /// </summary>
        public static string Color_DeepRed {
            get {
                return ResourceManager.GetString("Color_DeepRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色 的本地化字符串。
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅蓝 的本地化字符串。
        /// </summary>
        public static string Color_LightBlue {
            get {
                return ResourceManager.GetString("Color_LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，较淡 {1}% 的本地化字符串。
        /// </summary>
        public static string Color_LighterFormat {
            get {
                return ResourceManager.GetString("Color_LighterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海军蓝 的本地化字符串。
        /// </summary>
        public static string Color_Navy {
            get {
                return ResourceManager.GetString("Color_Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橙色 的本地化字符串。
        /// </summary>
        public static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橙红色 的本地化字符串。
        /// </summary>
        public static string Color_OrangeRed {
            get {
                return ResourceManager.GetString("Color_OrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫色 的本地化字符串。
        /// </summary>
        public static string Color_Purple {
            get {
                return ResourceManager.GetString("Color_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红色 的本地化字符串。
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青色 的本地化字符串。
        /// </summary>
        public static string Color_Teal {
            get {
                return ResourceManager.GetString("Color_Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫罗兰色 的本地化字符串。
        /// </summary>
        public static string Color_Violet {
            get {
                return ResourceManager.GetString("Color_Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白色 的本地化字符串。
        /// </summary>
        public static string Color_White {
            get {
                return ResourceManager.GetString("Color_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黄色 的本地化字符串。
        /// </summary>
        public static string Color_Yellow {
            get {
                return ResourceManager.GetString("Color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黄绿色 的本地化字符串。
        /// </summary>
        public static string Color_YellowGreen {
            get {
                return ResourceManager.GetString("Color_YellowGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string ColorGradientType_CustomGradient {
            get {
                return ResourceManager.GetString("ColorGradientType_CustomGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string ColorGradientType_Rainbow {
            get {
                return ResourceManager.GetString("ColorGradientType_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        public static string ColorPicker_AutomaticLabel {
            get {
                return ResourceManager.GetString("ColorPicker_AutomaticLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他颜色... 的本地化字符串。
        /// </summary>
        public static string ColorPicker_MoreColorsLabel {
            get {
                return ResourceManager.GetString("ColorPicker_MoreColorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无填充 的本地化字符串。
        /// </summary>
        public static string ColorPicker_NoFillLabel {
            get {
                return ResourceManager.GetString("ColorPicker_NoFillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置颜色 的本地化字符串。
        /// </summary>
        public static string ColorPicker_ResetSelectedColorLabel {
            get {
                return ResourceManager.GetString("ColorPicker_ResetSelectedColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准颜色 的本地化字符串。
        /// </summary>
        public static string ColorPicker_StandardColorsHeaderLabel {
            get {
                return ResourceManager.GetString("ColorPicker_StandardColorsHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题颜色 的本地化字符串。
        /// </summary>
        public static string ColorPicker_ThemeColorsHeaderLabel {
            get {
                return ResourceManager.GetString("ColorPicker_ThemeColorsHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Custom Map 的本地化字符串。
        /// </summary>
        public static string CustomSpaceGallery_DeleteMap_Desc {
            get {
                return ResourceManager.GetString("CustomSpaceGallery_DeleteMap_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit custom map 的本地化字符串。
        /// </summary>
        public static string CustomSpaceGallery_EditMap_Desc {
            get {
                return ResourceManager.GetString("CustomSpaceGallery_EditMap_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加筛选器 的本地化字符串。
        /// </summary>
        public static string FiltersTab_AddFiltersText {
            get {
                return ResourceManager.GetString("FiltersTab_AddFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string FiltersTab_AddSelectedFiltersText {
            get {
                return ResourceManager.GetString("FiltersTab_AddSelectedFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置高级筛选器 的本地化字符串。
        /// </summary>
        public static string FiltersTab_AdvancedFilterModeTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_AdvancedFilterModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示符合下列值的项目: 的本地化字符串。
        /// </summary>
        public static string FiltersTab_AdvancedFilterPromptText {
            get {
                return ResourceManager.GetString("FiltersTab_AdvancedFilterPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用筛选 的本地化字符串。
        /// </summary>
        public static string FiltersTab_ApplyAdvancedFilter {
            get {
                return ResourceManager.GetString("FiltersTab_ApplyAdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改聚合 的本地化字符串。
        /// </summary>
        public static string FiltersTab_ChangeAggFiltersTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_ChangeAggFiltersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除筛选 的本地化字符串。
        /// </summary>
        public static string FiltersTab_ClearFilterTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_ClearFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除搜索 的本地化字符串。
        /// </summary>
        public static string FiltersTab_ClearSearchButtonTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_ClearSearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_Is {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsAfter {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 早于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsBefore {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsBlank {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsNot {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非空白 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsNotBlank {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于或晚于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsOnOrAfter {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsOnOrAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于或早于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DateTimeFilterOperator_IsOnOrBefore {
            get {
                return ResourceManager.GetString("FiltersTab_DateTimeFilterOperator_IsOnOrBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除筛选 的本地化字符串。
        /// </summary>
        public static string FiltersTab_DeleteFilterTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_DeleteFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的平均值 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FieldAvgName {
            get {
                return ResourceManager.GetString("FiltersTab_FieldAvgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的计数 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FieldCountName {
            get {
                return ResourceManager.GetString("FiltersTab_FieldCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的最大值 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FieldMaxName {
            get {
                return ResourceManager.GetString("FiltersTab_FieldMaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的最小值 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FieldMinName {
            get {
                return ResourceManager.GetString("FiltersTab_FieldMinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的总和 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FieldSumName {
            get {
                return ResourceManager.GetString("FiltersTab_FieldSumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (全部) 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FilterAll {
            get {
                return ResourceManager.GetString("FiltersTab_FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (空白) 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FilterBlank {
            get {
                return ResourceManager.GetString("FiltersTab_FilterBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 且 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FilterPredicateOperator_And {
            get {
                return ResourceManager.GetString("FiltersTab_FilterPredicateOperator_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FilterPredicateOperator_Or {
            get {
                return ResourceManager.GetString("FiltersTab_FilterPredicateOperator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (选择所有搜索结果) 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FilterSearchAll {
            get {
                return ResourceManager.GetString("FiltersTab_FilterSearchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索... 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FilterSearchText {
            get {
                return ResourceManager.GetString("FiltersTab_FilterSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选器列表 的本地化字符串。
        /// </summary>
        public static string FiltersTab_FiltersListText {
            get {
                return ResourceManager.GetString("FiltersTab_FiltersListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置列表筛选器 的本地化字符串。
        /// </summary>
        public static string FiltersTab_ListFilterModeTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_ListFilterModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (未显示所有项目) 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NotAllShowingText {
            get {
                return ResourceManager.GetString("FiltersTab_NotAllShowingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_Is {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsBlank {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsGreaterThan {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于或等于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsLessThan {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于或等于 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsNot {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非空白 的本地化字符串。
        /// </summary>
        public static string FiltersTab_NumericFilterOperator_IsNotBlank {
            get {
                return ResourceManager.GetString("FiltersTab_NumericFilterOperator_IsNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 {0} 的本地化字符串。
        /// </summary>
        public static string FiltersTab_RangeFilter_ExactString {
            get {
                return ResourceManager.GetString("FiltersTab_RangeFilter_ExactString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介于 {0} 和 {1} 的本地化字符串。
        /// </summary>
        public static string FiltersTab_RangeFilter_RangeString {
            get {
                return ResourceManager.GetString("FiltersTab_RangeFilter_RangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置范围筛选器 的本地化字符串。
        /// </summary>
        public static string FiltersTab_RangeFilterModeTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_RangeFilterModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string FiltersTab_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("FiltersTab_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StatusAll {
            get {
                return ResourceManager.GetString("FiltersTab_StatusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已筛选 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StatusFiltered {
            get {
                return ResourceManager.GetString("FiltersTab_StatusFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可用的值 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StatusInvalidRange {
            get {
                return ResourceManager.GetString("FiltersTab_StatusInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理... 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StatusProcessing {
            get {
                return ResourceManager.GetString("FiltersTab_StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_Contains {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_DoesNotContain {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不以下列字符开头 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_DoesNotStartWith {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_Is {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_IsBlank {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_IsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_IsNot {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非空白 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_IsNotBlank {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_IsNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下列字符开头 的本地化字符串。
        /// </summary>
        public static string FiltersTab_StringFilterOperator_StartsWith {
            get {
                return ResourceManager.GetString("FiltersTab_StringFilterOperator_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string FiltersTab_UnknownPredicate {
            get {
                return ResourceManager.GetString("FiltersTab_UnknownPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string HelpIcon_ScaleX {
            get {
                return ResourceManager.GetString("HelpIcon_ScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string MainWindow_CloseTooltip {
            get {
                return ResourceManager.GetString("MainWindow_CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string MainWindow_HelpTooltip {
            get {
                return ResourceManager.GetString("MainWindow_HelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string MainWindow_MaximizeTooltip {
            get {
                return ResourceManager.GetString("MainWindow_MaximizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string MainWindow_MinimizeTooltip {
            get {
                return ResourceManager.GetString("MainWindow_MinimizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重做 的本地化字符串。
        /// </summary>
        public static string MainWindow_RedoTooltip {
            get {
                return ResourceManager.GetString("MainWindow_RedoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开或关闭菜单 的本地化字符串。
        /// </summary>
        public static string MainWindow_RibbonOptionsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_RibbonOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string MainWindow_UndoTooltip {
            get {
                return ResourceManager.GetString("MainWindow_UndoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图割算法 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_GraphCut {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_GraphCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSEG分割 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_JSEG {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_JSEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MeanShift分割 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_MS {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多尺度分割 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_MultiSeg {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_MultiSeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四叉树分割 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_QuadTree {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_QuadTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超像素分割 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_SuperPixel {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_SuperPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分水岭分割 的本地化字符串。
        /// </summary>
        public static string SegmentationAlogrithm_WaterShed {
            get {
                return ResourceManager.GetString("SegmentationAlogrithm_WaterShed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        public static string SendFeedbackText {
            get {
                return ResourceManager.GetString("SendFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        public static string StatusBar_DoneResolving {
            get {
                return ResourceManager.GetString("StatusBar_DoneResolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string StatusBar_ResolveCancelled {
            get {
                return ResourceManager.GetString("StatusBar_ResolveCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string StatusBar_ResolveFailed {
            get {
                return ResourceManager.GetString("StatusBar_ResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理 ... 的本地化字符串。
        /// </summary>
        public static string StatusBar_ResolvePending {
            get {
                return ResourceManager.GetString("StatusBar_ResolvePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理第 {0} 个，共 {1} 个 的本地化字符串。
        /// </summary>
        public static string StatusBar_Resolving {
            get {
                return ResourceManager.GetString("StatusBar_Resolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Day {
            get {
                return ResourceManager.GetString("TimeChunking_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Hour {
            get {
                return ResourceManager.GetString("TimeChunking_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Minute {
            get {
                return ResourceManager.GetString("TimeChunking_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Month {
            get {
                return ResourceManager.GetString("TimeChunking_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string TimeChunking_None {
            get {
                return ResourceManager.GetString("TimeChunking_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 季度 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Quarter {
            get {
                return ResourceManager.GetString("TimeChunking_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1:yyyy} 年 {0:MMM} - {1:MMM} 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Quarter_Format {
            get {
                return ResourceManager.GetString("TimeChunking_Quarter_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Second {
            get {
                return ResourceManager.GetString("TimeChunking_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string TimeChunking_Year {
            get {
                return ResourceManager.GetString("TimeChunking_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除图层 的本地化字符串。
        /// </summary>
        public static string Undo_DeleteLayer {
            get {
                return ResourceManager.GetString("Undo_DeleteLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动图层 的本地化字符串。
        /// </summary>
        public static string Undo_MoveLayer {
            get {
                return ResourceManager.GetString("Undo_MoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加图层 的本地化字符串。
        /// </summary>
        public static string Undo_NewLayer {
            get {
                return ResourceManager.GetString("Undo_NewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择图层 的本地化字符串。
        /// </summary>
        public static string Undo_SelectLayer {
            get {
                return ResourceManager.GetString("Undo_SelectLayer", resourceCulture);
            }
        }
    }
}
